import json
import os
import requests

def dispatch_soar_alert(alert_data):
    # Professional standard: Load webhook URLs from environment variables
    webhook_url = os.getenv("SOAR_WEBHOOK_URL", "https://webhook.site/mock-soc-channel")
    
    headers = {
        "Content-Type": "application/json",
        "X-SOC-Source": "Portable-Automation-Pipeline"
    }
    
    print("[*] Serializing alert payload to JSON schema...")
    payload = json.dumps(alert_data)
    
    try:
        print(f"[*] Dispatching webhook alert to SOAR endpoint...")
        # Production simulation using requests.post with timeout protection
        # response = requests.post(webhook_url, data=payload, headers=headers, timeout=5)
        
        # Simulating a successful HTTP 201 Created response
        class MockResponse:
            status_code = 201
            text = "Event accepted and routed to Tier-1 queue."
            
        response = MockResponse()
        
        if response.status_code in [200, 201, 202]:
            print(f"[+] Success: Webhook delivered. Response: {response.text}")
        else:
            print(f"[-] Warning: Webhook rejected with status code {response.status_code}")
            
    except requests.exceptions.Timeout:
        print("[-] Error: Webhook connection timed out.")
    except requests.exceptions.RequestException as e:
        print(f"[-] Critical Transmission Error: {e}")

# High-severity incident payload generated by your pipeline
incident_payload = {
    "incident_id": "INC-2026-9082",
    "severity": "CRITICAL",
    "threat_actor_ip": "192.168.100.45",
    "vector": "SSH Brute-Force",
    "action_taken": "Host isolated and firewall block rule applied",
    "analyst": "Automated SOC Pipeline"
}

dispatch_soar_alert(incident_payload)
